### ISSUE TITLE
Question: What is the purpose of `Width::Pointer`?

### ISSUE THREAD

**Issue by saona-raimundo** [udoprog/syntree#12]
Hi! Thanks for the crate!

I am not so familiar with `rowan` and wanted to ask what is the use of the `Width` associate type `Pointer`.

The method [`open`](https://docs.rs/syntree/0.14.5/syntree/struct.Builder.html#method.open) and [`token`](https://docs.rs/syntree/0.14.5/syntree/struct.Builder.html#method.token) return it if they succeed, but the example does not use them.

From [the example given in the `Width` trait](https://docs.rs/syntree/0.14.5/syntree/pointer/trait.Width.html#associatedtype.Pointer), I could not figure out the purpose of this type.

Thanks!

**Comment by udoprog** [comment]
It's the type used to adress nodes in a tree, there's an example in [`Node::id`](https://docs.rs/syntree/latest/syntree/struct.Node.html#method.id). One of its uses is to mark a node for deletion in a `ChangeSet`, but it could also be used for other external things that need to uniquely identify nodes.

**Comment by saona-raimundo** [comment]
Perfect! Thanks!
